// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P5.Data;

#nullable disable

namespace P5.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260828071506_SeedInventaireInitial")]
    partial class SeedInventaireInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("P5.Models.Marque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Marques");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Mazda"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Jeep"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Renault"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Ford"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Honda"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Volkswagen"
                        });
                });

            modelBuilder.Entity("P5.Models.ModeleVoiture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarqueId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MarqueId", "Nom")
                        .IsUnique();

                    b.ToTable("ModelesVoiture");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MarqueId = 1,
                            Nom = "Miata"
                        },
                        new
                        {
                            Id = 2,
                            MarqueId = 2,
                            Nom = "Liberty"
                        },
                        new
                        {
                            Id = 3,
                            MarqueId = 3,
                            Nom = "Scénic"
                        },
                        new
                        {
                            Id = 4,
                            MarqueId = 4,
                            Nom = "Explorer"
                        },
                        new
                        {
                            Id = 5,
                            MarqueId = 5,
                            Nom = "Civic"
                        },
                        new
                        {
                            Id = 6,
                            MarqueId = 6,
                            Nom = "GTI"
                        },
                        new
                        {
                            Id = 7,
                            MarqueId = 4,
                            Nom = "Edge"
                        });
                });

            modelBuilder.Entity("P5.Models.Reparation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cout")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Reparations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cout = 7600m,
                            Libelle = "Restauration complète",
                            VehiculeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cout = 350m,
                            Libelle = "Roulements des roues avant",
                            VehiculeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cout = 690m,
                            Libelle = "Radiateur, freins",
                            VehiculeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Cout = 1100m,
                            Libelle = "Pneus, freins",
                            VehiculeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Cout = 475m,
                            Libelle = "Climatisation, freins",
                            VehiculeId = 5
                        },
                        new
                        {
                            Id = 6,
                            Cout = 440m,
                            Libelle = "Pneus",
                            VehiculeId = 6
                        },
                        new
                        {
                            Id = 7,
                            Cout = 950m,
                            Libelle = "Pneus, freins, climatisation",
                            VehiculeId = 7
                        });
                });

            modelBuilder.Entity("P5.Models.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<string>("CodeVin")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<DateOnly>("DateAchat")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDisponibilite")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateVente")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Finition")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ModeleVoitureId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<decimal>("PrixAchat")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodeVin")
                        .IsUnique()
                        .HasFilter("[CodeVin] IS NOT NULL");

                    b.HasIndex("ModeleVoitureId");

                    b.ToTable("Vehicules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Annee = 2019,
                            DateAchat = new DateOnly(2022, 1, 7),
                            DateDisponibilite = new DateOnly(2022, 4, 7),
                            DateVente = new DateOnly(2022, 4, 8),
                            Finition = "LE",
                            ModeleVoitureId = 1,
                            PrixAchat = 1800m
                        },
                        new
                        {
                            Id = 2,
                            Annee = 2007,
                            DateAchat = new DateOnly(2022, 4, 2),
                            DateDisponibilite = new DateOnly(2022, 4, 7),
                            DateVente = new DateOnly(2022, 4, 9),
                            Finition = "Sport",
                            ModeleVoitureId = 2,
                            PrixAchat = 4500m
                        },
                        new
                        {
                            Id = 3,
                            Annee = 2007,
                            DateAchat = new DateOnly(2022, 4, 4),
                            DateDisponibilite = new DateOnly(2022, 4, 8),
                            Finition = "TCe",
                            ModeleVoitureId = 3,
                            PrixAchat = 1800m
                        },
                        new
                        {
                            Id = 4,
                            Annee = 2017,
                            DateAchat = new DateOnly(2022, 4, 5),
                            DateDisponibilite = new DateOnly(2022, 4, 9),
                            Finition = "XLT",
                            ModeleVoitureId = 4,
                            PrixAchat = 24350m
                        },
                        new
                        {
                            Id = 5,
                            Annee = 2008,
                            DateAchat = new DateOnly(2022, 4, 6),
                            DateDisponibilite = new DateOnly(2022, 4, 9),
                            DateVente = new DateOnly(2022, 4, 9),
                            Finition = "LX",
                            ModeleVoitureId = 5,
                            PrixAchat = 4000m
                        },
                        new
                        {
                            Id = 6,
                            Annee = 2016,
                            DateAchat = new DateOnly(2022, 4, 6),
                            DateDisponibilite = new DateOnly(2022, 4, 10),
                            DateVente = new DateOnly(2022, 4, 12),
                            Finition = "S",
                            ModeleVoitureId = 6,
                            PrixAchat = 15250m
                        },
                        new
                        {
                            Id = 7,
                            Annee = 2013,
                            DateAchat = new DateOnly(2022, 4, 7),
                            DateDisponibilite = new DateOnly(2022, 4, 11),
                            DateVente = new DateOnly(2022, 4, 12),
                            Finition = "SEL",
                            ModeleVoitureId = 7,
                            PrixAchat = 10990m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P5.Models.ModeleVoiture", b =>
                {
                    b.HasOne("P5.Models.Marque", "Marque")
                        .WithMany("Modeles")
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marque");
                });

            modelBuilder.Entity("P5.Models.Reparation", b =>
                {
                    b.HasOne("P5.Models.Vehicule", "Vehicule")
                        .WithMany("Reparations")
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("P5.Models.Vehicule", b =>
                {
                    b.HasOne("P5.Models.ModeleVoiture", "ModeleVoiture")
                        .WithMany("Vehicules")
                        .HasForeignKey("ModeleVoitureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModeleVoiture");
                });

            modelBuilder.Entity("P5.Models.Marque", b =>
                {
                    b.Navigation("Modeles");
                });

            modelBuilder.Entity("P5.Models.ModeleVoiture", b =>
                {
                    b.Navigation("Vehicules");
                });

            modelBuilder.Entity("P5.Models.Vehicule", b =>
                {
                    b.Navigation("Reparations");
                });
#pragma warning restore 612, 618
        }
    }
}
